replicaCount: 2

image:
  repository: muzzzic221/user-service
  tag: "v0.10"

container:
  port: 8001

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: arch.homework
      paths:
        - path: /health
          pathType: Exact
        - path: /user
          pathType: Exact
        - path: /user/[0-9]+
          pathType: ImplementationSpecific